angular.module("CatePage",["CateaPage"])
.config(function ($stateProvider) {
	$stateProvider
	.state({
		name:"index.cate",
		url:"/cate",
		templateUrl:"src/pages/cate/cate.html",
		css:{
			href:"src/pages/cate/cate.css",
			persist:true
		},
		controller:function ($scope,$http,$state) {
			$state.go("index.cate.cate-a")
		}
	})
	.state({
		name:"index.cate.cate-a",
		url:"/cate-a",
		templateUrl:"src/pages/cate/catea/cate-a.html",
		css:{
			href:"src/pages/cate/catea/cate-a.css",
			persist:true
		},
		controller:function ($scope,$http,$css) {
			$scope.catea= [];
			var getJob = $http.get("src/data/a.json");
			getJob.success(function (res) {
				$scope.catea = res.catea;
			})
		}
	})
	.state({
		name:"index.cate.cate-b",
		url:"/cate-b",
		templateUrl:"src/pages/cate/catea/cate-b.html",
		css:{
			href:"src/pages/cate/catea/cate-b.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-c",
		url:"/cate-c",
		templateUrl:"src/pages/cate/catea/cate-c.html",
		css:{
			href:"src/pages/cate/catea/cate-c.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-d",
		url:"/cate-d",
		templateUrl:"src/pages/cate/catea/cate-d.html",
		css:{
			href:"src/pages/cate/catea/cate-d.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-e",
		url:"/cate-e",
		templateUrl:"src/pages/cate/catea/cate-e.html",
		css:{
			href:"src/pages/cate/catea/cate-e.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-f",
		url:"/cate-f",
		templateUrl:"src/pages/cate/catea/cate-f.html",
		css:{
			href:"src/pages/cate/catea/cate-f.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-g",
		url:"/cate-g",
		templateUrl:"src/pages/cate/catea/cate-g.html",
		css:{
			href:"src/pages/cate/catea/cate-g.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-h",
		url:"/cate-h",
		templateUrl:"src/pages/cate/catea/cate-h.html",
		css:{
			href:"src/pages/cate/catea/cate-h.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-i",
		url:"/cate-i",
		templateUrl:"src/pages/cate/catea/cate-i.html",
		css:{
			href:"src/pages/cate/catea/cate-i.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-j",
		url:"/cate-j",
		templateUrl:"src/pages/cate/catea/cate-j.html",
		css:{
			href:"src/pages/cate/catea/cate-j.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-k",
		url:"/cate-k",
		templateUrl:"src/pages/cate/catea/cate-k.html",
		css:{
			href:"src/pages/cate/catea/cate-k.css",
			persist:true
		}
	})
	.state({
		name:"index.cate.cate-l",
		url:"/cate-l",
		templateUrl:"src/pages/cate/catea/cate-l.html",
		css:{
			href:"src/pages/cate/catea/cate-l.css",
			persist:true
		}
	})
})
